# Generated by Django 4.2.2 on 2023-06-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50000)),
                ('description', models.CharField(max_length=50000)),
                ('location', models.CharField(max_length=50000)),
                ('experience', models.CharField(max_length=50000)),
            ],
        ),
    ]
