# Generated by Django 4.2.2 on 2023-06-09 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='name',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='field1',
            field=models.CharField(default=datetime.datetime(2023, 6, 9, 11, 47, 45, 481136, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='field2',
            field=models.IntegerField(default=datetime.datetime(2023, 6, 9, 11, 47, 54, 386343, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
