# Generated by Django 4.2.2 on 2023-06-12 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='end_time',
            field=models.CharField(default=datetime.datetime(2023, 6, 12, 11, 41, 33, 143993, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='start_time',
            field=models.CharField(default=datetime.datetime(2023, 6, 12, 11, 41, 44, 75013, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
