# Generated by Django 4.2.2 on 2023-06-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_education_end_time_education_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_time',
        ),
    ]
