# Generated by Django 4.2.2 on 2023-06-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_mymodel_field1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='field1',
            new_name='name',
        ),
    ]
