# Generated by Django 4.2.2 on 2023-06-12 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_field1_mymodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='name',
            new_name='field1',
        ),
    ]
